### ISSUE TITLE
Correction sheet Checklist

### ISSUE THREAD

**Issue by Leofariasrj25** [NGINXcellent/webserv#98]
- Copiei a [lista de correção](https://rphlr.github.io/42-Evals/Rank05/webserv/) e estou adicionado abaixo de cada ponto se o requerimento está satisfeito e possíveis informações pertinentes.

(DONE) - concluído
(OPEN) - precisa ser verificado e de testes
(WARNING) - precisa de atenção
(ERROR) - deu ruim chefia

## Mandatory Part

-  [x] Launch the installation of siege with homebrew. (DONE)
    -   Possívelmente a idéia é levantar uma imagem de docker com o siege instalado
    

-   [x] Ask explanations about the basics of an HTTP server. (DONE)

-   [x] Ask what function the group used for I/O Multiplexing. (DONE)
    - answer: epoll 

-   [x] Ask for an explanation of how does select() (or equivalent) work. (DONE)
	   - answer: Através da monitoração de file descriptors que estão em uma fila, os FDs podem assumir uma série de eventos que sinalizam a entrada/saída de dados, conexão e desconexão, etc
   
-   [x] Ask if they use only one select() (or equivalent) and how they've managed the server to accept and the client to read/write. (DONE)
	   - Sim, através do controller que possui um loop ‘infinito’ onde epoll checa todas as conexões
    
-   [x] The select() (or equivalent) should be in the main loop and should check file descriptors for read and write AT THE SAME TIME. If not, the grade is 0 and the evaluation process ends now. (DONE)
	  - checamos por EPOLLIN e por EPOLLOUT no mesmo loop dentro de Controller essa info foi reforçada pelo chatgpt
    
-   [x] There should be only one read or one write per client per select() (or equivalent). Ask the group to show you the code from the select() (or equivalent) to the read and write of a client. (DONE)
    
	- a sendoToClient, chamada dentro da lógica do Controller assegura isto.

-   [x] #103
    
-   [x] #104
    
-   [x] If errno is checked after read/recv/write/send, the grade is 0 and the evaluation process ends now. (DONE)
	- não executamos verificações em errno 
    
-   [x] Writing or reading ANY file descriptor without going through the select() (or equivalent) is strictly FORBIDDEN. (DONE)
	- Qualquer operação de IO precisa passar pelo nosso Controller
    
-  [x]  The project must compile without any re-link issue. If not, use the 'Invalid compilation' flag. (DONE)

### Configuration

-   [x] Search for the HTTP response status codes list on the internet. During this evaluation, if any status codes is wrong, don't give any related points. (DONE)
	- Para os que implementamos, estão todos corretos de acordo com o ChatGPT

-   [x] #100

-   [x] #101

-  [x] Setup default error page (try to change the error 404). (DONE)

-  [x] Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit"). (OPEN)

- [x] Setup routes in a server to different directories. (DONE)

- [x] Setup a default file to search for if you ask for a directory. (DONE)

- [x] Setup a list of methods accepted for a certain route (e.g., try to delete something with and without permission) (DONE)

### Basic Checks
Using telnet, curl, prepared files, demonstrate that the following  
features work properly:

-   [x] GET, POST and DELETE requests should work. (DONE)

-   [x] UNKNOWN requests should not result in a crash. (DONE)

-   [x] For every test you should receive the appropriate status code. (DONE)

-   [x] Upload some file to the server and get it back. (DONE)

### Check CGI
**The server should never crash and an error should be visible in case of a problem.**

Pay attention to the following:

-   [x] The server is working fine using a CGI. (OPEN)

-   [x] With the help of the students you should check that everything is working properly. You have to test the CGI with the "GET" and "POST" methods. (OPEN)

-   [x] The CGI should be run in the correct directory for relative path file access. (OPEN)

-   [x] You need to test with files containing errors to see if the error handling works properly. You can use a script containing an infinite loop or an error; you are free to do whatever tests you want within the limits of acceptability that remain at your discretion. The group being evaluated should help you with this. (OPEN)

### Check with a browser

-   [x] Use the reference browser of the team. Open the network part of it, and try to connect to the server using it. (DONE)
	- Answer: Brave Browser.

-   [x] Look at the request header and response header. (DONE)

-   [x] It should be compatible to serve a fully static website. (DONE)

-   [x] Try a wrong URL on the server. (DONE)

-   [x] Try to list a directory. (DONE)

-   [x] Try a redirected URL. (DONE)

### Port issues

-  [x]  In the configuration file setup multiple ports and use different websites. Use the browser to ensure that the configuration works as expected and shows the right website. (OPEN)

-   [x] In the configuration, try to setup the same port multiple times. It should not work. (OPEN)

-   [x] Launch multiple servers at the same time with different configurations but with common ports. Does it work? If it does, ask why the server should work if one of the configurations isn't functional. Keep going. (OPEN)

#### Siege & stress test

-   [x] Use Siege to run some stress tests. (DONE)
-   [x] Availability should be above 99.5% for a simple GET on an empty page with a siege -b on that page. (DONE)
-   [x] Verify there is no memory leak (Monitor the process memory usage. It should not go up indefinitely). (DONE)
-   [x] Check if there is no hanging connection. (DONE)
-   [x] You should be able to use siege indefinitely without having to restart the server (take a look at siege -b). (DONE)

**Comment by Leofariasrj25** [comment]
### Configuration

-   Search for the HTTP response status codes list on the internet. During this evaluation, if any status codes is wrong, don't give any related points. (DONE)
	- Para os que implementamos, estão todos corretos de acordo com o ChatGPT

-   Setup multiple servers with different ports. (OPEN)

-   Setup multiple servers with different hostnames (use something like: curl --resolve example.com:80:127.0.0.1  [http://example.com/](http://example.com/)). (OPEN)

-  Setup default error page (try to change the error 404). (DONE)

-  Limit the client body (use: curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit").

- Setup routes in a server to different directories. (DONE)

- Setup a default file to search for if you ask for a directory. (DONE)

- Setup a list of methods accepted for a certain route (e.g., try to delete something with and without permission) (DONE)

**Comment by Leofariasrj25** [comment]
### Basic Checks
Using telnet, curl, prepared files, demonstrate that the following  
features work properly:

-   GET, POST and DELETE requests should work. (DONE)
-   UNKNOWN requests should not result in a crash. (DONE)
-   For every test you should receive the appropriate status code. (DONE)
-   Upload some file to the server and get it back. (DONE)

**Comment by Leofariasrj25** [comment]
### Check CGI
**The server should never crash and an error should be visible in case of a problem.**

Pay attention to the following:

-   The server is working fine using a CGI. (OPEN)
-   The CGI should be run in the correct directory for relative path file access. (OPEN)
-   With the help of the students you should check that everything is working properly. You have to test the CGI with the "GET" and "POST" methods. (OPEN)
-   You need to test with files containing errors to see if the error handling works properly. You can use a script containing an infinite loop or an error; you are free to do whatever tests you want within the limits of acceptability that remain at your discretion. The group being evaluated should help you with this. (OPEN)

**Comment by Leofariasrj25** [comment]
### Check with a browser

-   Use the reference browser of the team. Open the network part of it, and try to connect to the server using it. (DONE)
	- Answer: Brave Browser.
-   Look at the request header and response header. (DONE)
-   It should be compatible to serve a fully static website. (DONE)
-   Try a wrong URL on the server. (DONE)
-   Try to list a directory. (DONE)
-   Try a redirected URL. (DONE)
-   Try anything you want to.

**Comment by Leofariasrj25** [comment]
### Port issues

-   In the configuration file setup multiple ports and use different websites. Use the browser to ensure that the configuration works as expected and shows the right website. (OPEN)
-   In the configuration, try to setup the same port multiple times. It should not work. (OPEN)
-   Launch multiple servers at the same time with different configurations but with common ports. Does it work? If it does, ask why the server should work if one of the configurations isn't functional. Keep going. (OPEN)

**Comment by Leofariasrj25** [comment]
#### Siege & stress test

-   Use Siege to run some stress tests. (DONE)
-   Availability should be above 99.5% for a simple GET on an empty page with a siege -b on that page. (DONE)
-   Verify there is no memory leak (Monitor the process memory usage. It should not go up indefinitely). (DONE)
-   Check if there is no hanging connection. (DONE)
-   You should be able to use siege indefinitely without having to restart the server (take a look at siege -b). (DONE)

**Comment by Leofariasrj25** [comment]
DONE! 

We still need to add some bells and whistles.
